//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORS_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssociateDetails
    {
        public int ID { get; set; }
        public Nullable<int> AssociateID { get; set; }
        public string AssociateName { get; set; }
        public string Designation { get; set; }
        public string Location { get; set; }
        public string BU { get; set; }
    }
}
