//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORS_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Email
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public string Emailaddress { get; set; }
        public string EventID { get; set; }
        public Nullable<bool> EmailStatus { get; set; }
        public string EmailType { get; set; }
        public System.DateTime GeneratedDate { get; set; }
    }
}
