//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORS_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventVolunteerDetails
    {
        public int ID { get; set; }
        public string EventID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string BU { get; set; }
        public Nullable<int> VolunteerHours { get; set; }
        public Nullable<int> TravelHours { get; set; }
        public Nullable<int> LivesImpacted { get; set; }
    }
}
