//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORS_Model
{
    using System;
    
    public partial class GenericMetricsReport
    {
        public string TotalNoOfVolunteers { get; set; }
        public string TotalVolunteerHours { get; set; }
        public string TotalTravelHours { get; set; }
        public string OverallVolunteeringHours { get; set; }
        public string IntervalRange { get; set; }
    }
}
