//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORS_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OutReachEventInformation
    {
        public int ID { get; set; }
        public string EventID { get; set; }
        public string BaseLocation { get; set; }
        public string BeneficiaryName { get; set; }
        public string CouncilName { get; set; }
        public string EventName { get; set; }
        public string EventDescription { get; set; }
        public string EventDate { get; set; }
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public Nullable<double> VolunteerHours { get; set; }
        public Nullable<double> TravelHours { get; set; }
        public Nullable<double> LivesImpacted { get; set; }
        public string BusinessUnit { get; set; }
        public string Status { get; set; }
        public string IIEPCategory { get; set; }
        public Nullable<bool> IsProcessed { get; set; }
    }
}
