//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORS_Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class POC_Credential
    {
        public int EmployeeID { get; set; }
        public string Password { get; set; }
    
        public virtual Employee_Details Employee_Details { get; set; }
    }
}
