//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ORS_Model
{
    using System;
    
    public partial class spGetGenericMetrics_Result2
    {
        public Nullable<double> TotalNoOfVolunteers { get; set; }
        public Nullable<double> TotalVolunteerHours { get; set; }
        public Nullable<double> TotalTravelHours { get; set; }
        public Nullable<double> OverallVolunteeringHours { get; set; }
        public string IntervalRange { get; set; }
    }
}
